#
# Copyright (C) 2011
#
# Brick Yang <printfxxx@163.com>
#
# This program is free software. You can redistribute it and/or
# modify it as you like.
#

##
# File		gcc.c.mk
# Brief		Rules for generate header files with gcc.
#

ifeq ($(EXTMF_SEG),V)

define do_hdr
$(strip (echo "/* Automatically generated by mconf.mk, do not edit */" &&
echo -e "#ifndef _$(notdir $(1))_\n#define _$(notdir $(1))_\n" | sed -e "s/\s.*/\U&/" -e "s/\./_/g";
[ "$${PIPESTATUS[*]}" == "0 0" ] && $(CC) -E -P -dM -ansi -undef $(2) -xc /dev/null | sed -e "/_STDC_/d";
[ "$${PIPESTATUS[*]}" == "0 0" ] && echo -e "\n#endif") > $(1) || ($(RM) $(1); false))
endef

HDR = $(filter %$(SFX_H),$(_obj))

endif	# ifeq ($(EXTMF_SEG),V)

ifeq ($(EXTMF_SEG),R)

ifeq ($(filter $(NOINIT_TARGET),$(MAKECMDGOALS)),)
$(shell mkdir -p $(addprefix $(gendir),$(sort $(dir $(HDR)) ./)))
endif

$(OBJ:%=$(bdir)%) $(DIR:%/=build-%): $(HDR:%=$(gendir)%)

$(HDR:%=$(bdir)%$(SFX_CMD)): $(bdir)%$(SFX_CMD): FORCE
	$(call cmd_change_chk,$(call do_hdr,$(gendir)$*,$(cflags_$*)),$@)

$(HDR:%=$(gendir)%): $(gendir)%: $(bdir)%$(SFX_CMD)
	$(call msg,HDR,$(@:$(gendir)%=%))
	$(call do_hdr,$@,$(cflags_$*))

endif	# ifeq ($(EXTMF_SEG),R)
